import { Prisma } from "@prisma/client";
import { getSharedPrismaClient } from "@/lib/prisma";
import type { LeadPilotAIOS } from "@/lib/ai-os";
import type { ConversationEvent, TimelineCategory } from "@/lib/timeline-engine";

/**
 * Intelligence Persistence Layer (Durable / Prisma-backed).
 *
 * Replaces the previous in-memory Map store. Intelligence generated by the AI OS
 * after every assistant response is now persisted to Postgres so it survives
 * page refreshes, server restarts, HMR, multiple workers and production
 * deployments. The public API (function names + returned shapes) is unchanged
 * except that every function is now async. Nothing here changes AI behaviour —
 * it only stores what runAIOS produced.
 *
 * conversationId is the shared relationship key; we never duplicate the base
 * Conversation / Lead tables.
 */

export interface ConversationIntelligenceRecord {
  summary: string;
  visitorSummary: string;
  businessSummary: string;
  painPoints: string[];
  goals: string[];
  interests: string[];
  productsDiscussed: string[];
  objections: string[];
  positiveSignals: string[];
  negativeSignals: string[];
  nextRecommendedStep: string;
  conversationQuality: string;
  engagementScore: number;
}

export interface LeadProfileRecord {
  leadScore: number;
  qualification: string;
  scoreReasons: string[];
  completedObjectives: string[];
  pendingObjectives: string[];
  visitorStage?: string;
  currentGoal: string;
  currentStrategy: string;
  recommendedAction: string;
  currentMission: string;
  confidence: number;
}

export interface BusinessProfileRecord {
  industry?: string;
  businessType?: string;
  services?: string[];
  company?: string;
  location?: string;
  products?: string[];
  communicationStyle?: string;
  technicalLevel?: string;
}

export interface AnalyticsRecord {
  leadTrend: number[];
  qualificationHistory: string[];
  engagementHistory: number[];
  conversationQualityHistory: string[];
  goalProgressHistory: number[];
}

/** A fully assembled per-conversation bundle for aggregation/analytics. */
export interface PersistedConversation {
  conversationId: string;
  projectId?: string;
  lead?: LeadProfileRecord;
  business?: BusinessProfileRecord;
  conversation?: ConversationIntelligenceRecord;
  timeline: ConversationEvent[];
  analytics?: AnalyticsRecord;
}

function json(value: unknown): Prisma.InputJsonValue {
  return value as Prisma.InputJsonValue;
}

// --- Conversation Intelligence -------------------------------------------

export async function loadConversationIntelligence(
  conversationId: string
): Promise<ConversationIntelligenceRecord | null> {
  const prisma = getSharedPrismaClient();
  const row = await prisma.conversationIntelligence.findUnique({ where: { conversationId } });
  return row ? (row.data as unknown as ConversationIntelligenceRecord) : null;
}

export async function saveConversationIntelligence(
  conversationId: string,
  record: ConversationIntelligenceRecord,
  projectId?: string
): Promise<void> {
  const prisma = getSharedPrismaClient();
  await prisma.conversationIntelligence.upsert({
    where: { conversationId },
    create: { conversationId, projectId: projectId ?? null, data: json(record) },
    update: { data: json(record), projectId: projectId ? projectId : undefined }
  });
}

export async function updateConversationIntelligence(
  conversationId: string,
  partial: Partial<ConversationIntelligenceRecord>
): Promise<void> {
  const existing = await loadConversationIntelligence(conversationId);
  const next: ConversationIntelligenceRecord = {
    ...(existing ?? ({} as ConversationIntelligenceRecord)),
    ...partial
  };
  await saveConversationIntelligence(conversationId, next);
}

// --- Lead Profile ---------------------------------------------------------

export async function loadLeadProfile(conversationId: string): Promise<LeadProfileRecord | null> {
  const prisma = getSharedPrismaClient();
  const row = await prisma.leadProfile.findUnique({ where: { conversationId } });
  return row ? (row.data as unknown as LeadProfileRecord) : null;
}

export async function saveLeadProfile(
  conversationId: string,
  record: LeadProfileRecord,
  projectId?: string
): Promise<void> {
  const prisma = getSharedPrismaClient();
  await prisma.leadProfile.upsert({
    where: { conversationId },
    create: { conversationId, projectId: projectId ?? null, data: json(record) },
    update: { data: json(record), projectId: projectId ? projectId : undefined }
  });
}

// --- Business Profile -----------------------------------------------------

export async function loadBusinessProfile(conversationId: string): Promise<BusinessProfileRecord | null> {
  const prisma = getSharedPrismaClient();
  const row = await prisma.businessProfile.findUnique({ where: { conversationId } });
  return row ? (row.data as unknown as BusinessProfileRecord) : null;
}

export async function saveBusinessProfile(
  conversationId: string,
  record: BusinessProfileRecord,
  projectId?: string
): Promise<void> {
  const prisma = getSharedPrismaClient();
  await prisma.businessProfile.upsert({
    where: { conversationId },
    create: { conversationId, projectId: projectId ?? null, data: json(record) },
    update: { data: json(record), projectId: projectId ? projectId : undefined }
  });
}

// --- Timeline -------------------------------------------------------------

export async function loadTimeline(conversationId: string): Promise<ConversationEvent[]> {
  const prisma = getSharedPrismaClient();
  const rows = await prisma.timelineEvent.findMany({
    where: { conversationId },
    orderBy: { timestamp: "asc" }
  });
  return rows.map((r) => ({
    timestamp: r.timestamp.toISOString(),
    event: r.event,
    description: r.description,
    category: r.category as TimelineCategory,
    importance: r.importance
  }));
}

/** Appends only events not already present (avoids duplicates). */
export async function appendTimelineEvent(
  conversationId: string,
  events: ConversationEvent[],
  projectId?: string
): Promise<void> {
  if (events.length === 0) return;
  const prisma = getSharedPrismaClient();

  const existing = await prisma.timelineEvent.findMany({
    where: { conversationId },
    select: { event: true, description: true }
  });
  const seen = new Set(existing.map((e) => `${e.event}::${e.description}`));

  const toInsert = events
    .filter((e) => {
      const key = `${e.event}::${e.description}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map((e) => ({
      conversationId,
      projectId: projectId ?? null,
      event: e.event,
      description: e.description,
      category: e.category,
      importance: e.importance,
      timestamp: new Date(e.timestamp)
    }));

  if (toInsert.length === 0) return;

  // skipDuplicates guarantees only genuinely new events are inserted even
  // under concurrent writes (the unique constraint backs this up).
  await prisma.timelineEvent.createMany({ data: toInsert, skipDuplicates: true });
}

// --- Analytics Snapshot ---------------------------------------------------

export async function loadAnalyticsSnapshot(conversationId: string): Promise<AnalyticsRecord | null> {
  const prisma = getSharedPrismaClient();
  const row = await prisma.analyticsSnapshot.findUnique({ where: { conversationId } });
  return row ? (row.data as unknown as AnalyticsRecord) : null;
}

/** Appends current metrics to the historical series, skipping unchanged tails. */
export async function updateAnalyticsSnapshot(
  conversationId: string,
  current: {
    leadScore: number;
    qualification: string;
    engagementScore: number;
    conversationQuality: string;
    goalProgress: number;
  },
  projectId?: string
): Promise<void> {
  const prisma = getSharedPrismaClient();
  const existing = await loadAnalyticsSnapshot(conversationId);
  const base: AnalyticsRecord = existing ?? {
    leadTrend: [],
    qualificationHistory: [],
    engagementHistory: [],
    conversationQualityHistory: [],
    goalProgressHistory: []
  };

  const next: AnalyticsRecord = {
    leadTrend: appendUnique(base.leadTrend, current.leadScore, (a, b) => a === b),
    qualificationHistory: appendUnique(base.qualificationHistory, current.qualification, (a, b) => a === b),
    engagementHistory: appendUnique(base.engagementHistory, current.engagementScore, (a, b) => a === b),
    conversationQualityHistory: appendUnique(
      base.conversationQualityHistory,
      current.conversationQuality,
      (a, b) => a === b
    ),
    goalProgressHistory: appendUnique(base.goalProgressHistory, current.goalProgress, (a, b) => a === b)
  };

  await prisma.analyticsSnapshot.upsert({
    where: { conversationId },
    create: { conversationId, projectId: projectId ?? null, data: json(next) },
    update: { data: json(next), projectId: projectId ? projectId : undefined }
  });
}

// --- Orchestrated persistence --------------------------------------------

/**
 * Persists the full intelligence produced by runAIOS. Called once after the
 * OS runs; the route does not need to know storage details.
 */
export async function persistConversation(
  conversationId: string,
  aiOS: LeadPilotAIOS,
  projectId?: string
): Promise<void> {
  const prisma = getSharedPrismaClient();

  // Conversation Intelligence
  const ci = aiOS.conversation;
  await saveConversationIntelligence(
    conversationId,
    {
      summary: ci.summary,
      visitorSummary: ci.visitorSummary,
      businessSummary: ci.businessSummary,
      painPoints: ci.painPoints,
      goals: ci.goals,
      interests: ci.interests,
      productsDiscussed: ci.productsDiscussed,
      objections: ci.objections,
      positiveSignals: ci.positiveSignals,
      negativeSignals: ci.negativeSignals,
      nextRecommendedStep: ci.nextRecommendedStep,
      conversationQuality: ci.conversationQuality,
      engagementScore: ci.engagementScore
    },
    projectId
  );

  // Lead Profile
  const lead = aiOS.lead;
  await saveLeadProfile(
    conversationId,
    {
      leadScore: lead.score,
      qualification: lead.qualification,
      scoreReasons: lead.scoreReasons,
      completedObjectives: lead.completedObjectives,
      pendingObjectives: lead.pendingObjectives,
      visitorStage: aiOS.state.stage,
      currentGoal: aiOS.goal.goal,
      currentStrategy: aiOS.strategy.strategy,
      recommendedAction: aiOS.nextAction.action,
      currentMission: aiOS.salesDecision.currentMission,
      confidence: aiOS.salesDecision.confidence
    },
    projectId
  );

  // Business Profile
  const memory = aiOS.memory;
  const business = aiOS.business;
  await saveBusinessProfile(
    conversationId,
    {
      industry: memory.industry ?? business.industry,
      businessType: memory.businessType ?? business.type,
      services: memory.productsInterested,
      company: memory.company ?? business.company,
      location: memory.location,
      products: memory.productsInterested,
      communicationStyle: undefined,
      technicalLevel: undefined
    },
    projectId
  );

  // Timeline (append only, deduplicated)
  await appendTimelineEvent(conversationId, aiOS.timeline, projectId);

  // Analytics Snapshot
  await updateAnalyticsSnapshot(
    conversationId,
    {
      leadScore: lead.score,
      qualification: lead.qualification,
      engagementScore: ci.engagementScore,
      conversationQuality: ci.conversationQuality,
      goalProgress: aiOS.analytics.goalProgress
    },
    projectId
  );
}

/**
 * Explicitly associate a conversation with a project when project context is
 * known independently of an AIOS run.
 */
export async function setConversationProject(conversationId: string, projectId: string): Promise<void> {
  const prisma = getSharedPrismaClient();
  const data = { projectId };
  await Promise.all([
    prisma.conversationIntelligence.updateMany({ where: { conversationId }, data }),
    prisma.leadProfile.updateMany({ where: { conversationId }, data }),
    prisma.businessProfile.updateMany({ where: { conversationId }, data }),
    prisma.analyticsSnapshot.updateMany({ where: { conversationId }, data }),
    prisma.timelineEvent.updateMany({ where: { conversationId }, data })
  ]);
}

// --- Bulk reads (analytics + CRM aggregation) ----------------------------

async function loadAll(where?: { projectId: string }): Promise<PersistedConversation[]> {
  const prisma = getSharedPrismaClient();
  const w = where ? { projectId: where.projectId } : {};

  const [ciRows, leadRows, bizRows, analyticsRows, timelineRows] = await Promise.all([
    prisma.conversationIntelligence.findMany({ where: w }),
    prisma.leadProfile.findMany({ where: w }),
    prisma.businessProfile.findMany({ where: w }),
    prisma.analyticsSnapshot.findMany({ where: w }),
    prisma.timelineEvent.findMany({ where: w, orderBy: { timestamp: "asc" } })
  ]);

  const map = new Map<string, PersistedConversation>();
  const ensure = (id: string): PersistedConversation => {
    let r = map.get(id);
    if (!r) {
      r = { conversationId: id, timeline: [] };
      map.set(id, r);
    }
    return r;
  };

  for (const row of ciRows) {
    const r = ensure(row.conversationId);
    r.projectId = row.projectId ?? r.projectId;
    r.conversation = row.data as unknown as ConversationIntelligenceRecord;
  }
  for (const row of leadRows) {
    const r = ensure(row.conversationId);
    r.projectId = row.projectId ?? r.projectId;
    r.lead = row.data as unknown as LeadProfileRecord;
  }
  for (const row of bizRows) {
    const r = ensure(row.conversationId);
    r.projectId = row.projectId ?? r.projectId;
    r.business = row.data as unknown as BusinessProfileRecord;
  }
  for (const row of analyticsRows) {
    const r = ensure(row.conversationId);
    r.projectId = row.projectId ?? r.projectId;
    r.analytics = row.data as unknown as AnalyticsRecord;
  }
  for (const row of timelineRows) {
    const r = ensure(row.conversationId);
    r.timeline.push({
      timestamp: row.timestamp.toISOString(),
      event: row.event,
      description: row.description,
      category: row.category as TimelineCategory,
      importance: row.importance
    });
  }

  return [...map.values()];
}

/**
 * Read every persisted conversation bundle. Used by the analytics layer to
 * aggregate intelligence. Returns an empty array when nothing is persisted.
 */
export async function getAllPersisted(): Promise<PersistedConversation[]> {
  return loadAll();
}

/** Read all persisted bundles scoped to a single project. */
export async function getAllPersistedForProject(projectId: string): Promise<PersistedConversation[]> {
  return loadAll({ projectId });
}

function appendUnique<T>(arr: T[], value: T, eq: (a: T, b: T) => boolean): T[] {
  if (arr.length === 0 || !eq(arr[arr.length - 1], value)) return [...arr, value];
  return arr;
}
