import type { LeadPilotAIOS } from "@/lib/ai-os";
import type { ConversationEvent } from "@/lib/timeline-engine";

/**
 * Intelligence Persistence Layer.
 *
 * Persists the intelligence already generated by the AI OS after every
 * assistant response. Storage is currently an in-memory Map so the database
 * schema is untouched; callers depend only on this module, so it can later be
 * swapped for Prisma without changing the route or engines.
 *
 * Nothing here changes AI behaviour — it only stores what runAIOS produced.
 */

export interface ConversationIntelligenceRecord {
  summary: string;
  visitorSummary: string;
  businessSummary: string;
  painPoints: string[];
  goals: string[];
  interests: string[];
  productsDiscussed: string[];
  objections: string[];
  positiveSignals: string[];
  negativeSignals: string[];
  nextRecommendedStep: string;
  conversationQuality: string;
  engagementScore: number;
}

export interface LeadProfileRecord {
  leadScore: number;
  qualification: string;
  scoreReasons: string[];
  completedObjectives: string[];
  pendingObjectives: string[];
  visitorStage?: string;
  currentGoal: string;
  currentStrategy: string;
  recommendedAction: string;
  currentMission: string;
  confidence: number;
}

export interface BusinessProfileRecord {
  industry?: string;
  businessType?: string;
  services?: string[];
  company?: string;
  location?: string;
  products?: string[];
  communicationStyle?: string;
  technicalLevel?: string;
}

export interface AnalyticsRecord {
  leadTrend: number[];
  qualificationHistory: string[];
  engagementHistory: number[];
  conversationQualityHistory: string[];
  goalProgressHistory: number[];
}

// --- In-memory storage (replaceable later) -------------------------------

const conversationIntelStore = new Map<string, ConversationIntelligenceRecord>();
const leadProfileStore = new Map<string, LeadProfileRecord>();
const businessProfileStore = new Map<string, BusinessProfileRecord>();
const timelineStore = new Map<string, ConversationEvent[]>();
const analyticsStore = new Map<string, AnalyticsRecord>();

function appendUnique<T>(arr: T[], value: T, eq: (a: T, b: T) => boolean): T[] {
  if (arr.length === 0 || !eq(arr[arr.length - 1], value)) return [...arr, value];
  return arr;
}

// --- Conversation Intelligence -------------------------------------------

export function loadConversationIntelligence(conversationId: string): ConversationIntelligenceRecord | null {
  return conversationIntelStore.get(conversationId) ?? null;
}

export function saveConversationIntelligence(
  conversationId: string,
  record: ConversationIntelligenceRecord
): void {
  conversationIntelStore.set(conversationId, record);
}

export function updateConversationIntelligence(
  conversationId: string,
  partial: Partial<ConversationIntelligenceRecord>
): void {
  const existing = conversationIntelStore.get(conversationId) ?? ({} as ConversationIntelligenceRecord);
  conversationIntelStore.set(conversationId, { ...existing, ...partial });
}

// --- Lead Profile ---------------------------------------------------------

export function loadLeadProfile(conversationId: string): LeadProfileRecord | null {
  return leadProfileStore.get(conversationId) ?? null;
}

export function saveLeadProfile(conversationId: string, record: LeadProfileRecord): void {
  leadProfileStore.set(conversationId, record);
}

// --- Business Profile -----------------------------------------------------

export function loadBusinessProfile(conversationId: string): BusinessProfileRecord | null {
  return businessProfileStore.get(conversationId) ?? null;
}

export function saveBusinessProfile(conversationId: string, record: BusinessProfileRecord): void {
  businessProfileStore.set(conversationId, record);
}

// --- Timeline -------------------------------------------------------------

export function loadTimeline(conversationId: string): ConversationEvent[] {
  return timelineStore.get(conversationId) ?? [];
}

/** Appends only events not already present (avoids duplicates). */
export function appendTimelineEvent(
  conversationId: string,
  events: ConversationEvent[]
): void {
  const existing = timelineStore.get(conversationId) ?? [];
  const seen = new Set(existing.map((e) => `${e.event}::${e.description}`));
  const added = events.filter((e) => {
    const key = `${e.event}::${e.description}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
  if (added.length > 0) {
    timelineStore.set(conversationId, [...existing, ...added]);
  }
}

// --- Analytics Snapshot ---------------------------------------------------

export function loadAnalyticsSnapshot(conversationId: string): AnalyticsRecord | null {
  return analyticsStore.get(conversationId) ?? null;
}

/** Appends current metrics to the historical series, skipping unchanged tails. */
export function updateAnalyticsSnapshot(
  conversationId: string,
  current: {
    leadScore: number;
    qualification: string;
    engagementScore: number;
    conversationQuality: string;
    goalProgress: number;
  }
): void {
  const existing = analyticsStore.get(conversationId) ?? {
    leadTrend: [],
    qualificationHistory: [],
    engagementHistory: [],
    conversationQualityHistory: [],
    goalProgressHistory: [],
  };

  const next: AnalyticsRecord = {
    leadTrend: appendUnique(existing.leadTrend, current.leadScore, (a, b) => a === b),
    qualificationHistory: appendUnique(existing.qualificationHistory, current.qualification, (a, b) => a === b),
    engagementHistory: appendUnique(existing.engagementHistory, current.engagementScore, (a, b) => a === b),
    conversationQualityHistory: appendUnique(
      existing.conversationQualityHistory,
      current.conversationQuality,
      (a, b) => a === b
    ),
    goalProgressHistory: appendUnique(existing.goalProgressHistory, current.goalProgress, (a, b) => a === b),
  };

  analyticsStore.set(conversationId, next);
}

// --- Orchestrated persistence --------------------------------------------

/**
 * Persists the full intelligence produced by runAIOS. Called once after the
 * OS runs; the route does not need to know storage details.
 */
export function persistConversation(conversationId: string, aiOS: LeadPilotAIOS): void {
  // Conversation Intelligence
  const ci = aiOS.conversation;
  saveConversationIntelligence(conversationId, {
    summary: ci.summary,
    visitorSummary: ci.visitorSummary,
    businessSummary: ci.businessSummary,
    painPoints: ci.painPoints,
    goals: ci.goals,
    interests: ci.interests,
    productsDiscussed: ci.productsDiscussed,
    objections: ci.objections,
    positiveSignals: ci.positiveSignals,
    negativeSignals: ci.negativeSignals,
    nextRecommendedStep: ci.nextRecommendedStep,
    conversationQuality: ci.conversationQuality,
    engagementScore: ci.engagementScore,
  });

  // Lead Profile
  const lead = aiOS.lead;
  saveLeadProfile(conversationId, {
    leadScore: lead.score,
    qualification: lead.qualification,
    scoreReasons: lead.scoreReasons,
    completedObjectives: lead.completedObjectives,
    pendingObjectives: lead.pendingObjectives,
    visitorStage: aiOS.state.stage,
    currentGoal: aiOS.goal.goal,
    currentStrategy: aiOS.strategy.strategy,
    recommendedAction: aiOS.nextAction.action,
    currentMission: aiOS.salesDecision.currentMission,
    confidence: aiOS.salesDecision.confidence,
  });

  // Business Profile
  const memory = aiOS.memory;
  const business = aiOS.business;
  saveBusinessProfile(conversationId, {
    industry: memory.industry ?? business.industry,
    businessType: memory.businessType ?? business.type,
    services: memory.productsInterested,
    company: memory.company ?? business.company,
    location: memory.location,
    products: memory.productsInterested,
    communicationStyle: undefined,
    technicalLevel: undefined,
  });

  // Timeline (append only, deduplicated)
  appendTimelineEvent(conversationId, aiOS.timeline);

  // Analytics Snapshot
  updateAnalyticsSnapshot(conversationId, {
    leadScore: lead.score,
    qualification: lead.qualification,
    engagementScore: ci.engagementScore,
    conversationQuality: ci.conversationQuality,
    goalProgress: aiOS.analytics.goalProgress,
  });
}
